
name: generate_snake
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v3.4.1
